sudo: required

services:
  - docker

dist: trusty

language: c++ # to avoid using /opt/python from travis

# for Travis {{{
cache:
  directories:
    - $HOME/.ccache
    - $HOME/.cache/pip
    - $HOME/.ros/data
# }}}

env:
  global:
    - CATKIN_TOOLS_CONFIG_OPTIONS="--blacklist imagesift jsk_recognition_msgs jsk_perception jsk_pcl_ros_utils jsk_pcl_ros resized_image_transport checkerboard_detector fetcheus naoqieus jsk_fetch_startup jsk_nao_startup roseus_remote jsk_robot_startup jsk_robot_utils jsk_pr2_calibration pr2_base_trajectory_action jsk_baxter_web peppereus naoeus jsk_baxter_desktop jsk_pepper_startup jsk_pr2_startup jsk_pr2_desktop"
    - NOT_TEST_INSTALL=true
    - ROS_PARALLEL_JOBS="-j2"
    - ROSDEP_ADDITIONAL_OPTIONS="-n -q --ignore-src --skip-keys=jsk_smart_gui --skip-keys=ros3djs --skip-keys=pr2_calibration_launch --skip-keys=jsk_android_gui_api9 --skip-keys=ros2djs --skip-keys=face_recognition --skip-keys=roslibjs --skip-keys=force_proximity_ros --skip-keys=safe_teleop_base --skip-keys=pcl"
    - USE_DEB=false
    - USE_DOCKER=true
    - USE_TRAVIS=true
    # XXX: hotfix for chainer problem (https://github.com/chainer/chainer/issues/8545)
    - BEFORE_SCRIPT='sudo -H pip install chainer==6.7.0 gdown==3.10.1'
  matrix:
    - ROS_DISTRO=indigo
    - ROS_DISTRO=indigo BUILD_PKGS="jsk_apc2015_common jsk_apc2016_common jsk_arc2017_common jsk_2015_05_baxter_apc jsk_2016_01_baxter_apc jsk_arc2017_baxter selective_dualarm_stowing sphand_driver sphand_driver_msgs vl53l0x_mraa_ros"
    - ROS_DISTRO=kinetic
    - ROS_DISTRO=melodic
matrix:
  allow_failures:
    - env: ROS_DISTRO=indigo
script:
  - export DOCKER_IMAGE="jskrobotics/jsk_apc:${ROS_DISTRO}-latest-testing"
  # build & test ROS packages
  - source .travis/travis.sh
  # build doc
  - cd $TRAVIS_BUILD_DIR/doc
  - source setup.sh
  - make html

after_script:
  # trigger the build of the docker image
  # If the test fails, new docker image can be helpful,
  # so it should be triggered at both after_success and failure.
  - curl -X POST https://registry.hub.docker.com/u/jskrobotics/jsk_apc/trigger/c4af5c9a-cf54-45b1-8beb-ccba5a102a1f/

notifications:
  email:
    on_success: always
    on_failure: always
  slack: jsk-robotics:Av7tc8wj3IWkLYvlTzHE7x2g

# to weaken the load on the Jenkins server
branches:
  only:
    - master
