sudo: false  # jenkins
# sudo: required  # travis

# dist: trusty  # travis

language: generic

# cache:  # travis
#   directories:  # travis
#     - $HOME/.ccache  # travis
#     - $HOME/.cache/pip  # travis
#     - $HOME/.ros/test_data  # travis

env:
  global:
#    - USE_TRAVIS=true  # travis
    - BUILDER=catkin
    - NO_SUDO=true  # jenkins
    - NOT_TEST_INSTALL=true
    - USE_DEB=false
    - ROS_PARALLEL_JOBS="-j8"  # jenkins
#    - ROS_PARALLEL_JOBS="-j2"  # travis
    - ROSWS=wstool
    - ROSDEP_ADDITIONAL_OPTIONS="-q -n --ignore-src"
  matrix:
    - ROS_DISTRO=indigo

script:
  # build & test ROS packages
  - source .travis/travis.sh
  # build doc
  - cd $TRAVIS_BUILD_DIR/doc
  - unset PYTHONPATH  # cleanup for virtualenv
  - source setup.sh
  - make html

notifications:
  email:
    on_success: always
    on_failure: always
  slack: jsk-robotics:Av7tc8wj3IWkLYvlTzHE7x2g
