sudo: required

dist: trusty

language: c++ # to avoid using /opt/python from travis

cache:
  directories:
    - $HOME/.ccache
    - $HOME/.cache/pip
    - $HOME/.ros/data

env:
  global:
    - CATKIN_TOOLS_CONFIG_OPTIONS="--blacklist imagesift jsk_recognition_msgs jsk_perception jsk_pcl_ros_utils jsk_pcl_ros resized_image_transport checkerboard_detector fetcheus naoqieus jsk_fetch_startup jsk_nao_startup roseus_remote jsk_robot_start jsk_robot_utils jsk_pr2_calibration pr2_base_trajectory_action jsk_baxter_web peppereus naoeus"
    - NOT_TEST_INSTALL=true
    - ROS_PARALLEL_JOBS="-j2"
    - ROSDEP_ADDITIONAL_OPTIONS="-n -q --ignore-src --skip-keys=jsk_smart_gui --skip-keys=ros3djs --skip-keys=pr2_calibration_launch --skip-keys=jsk_android_gui_api9 --skip-keys=ros2djs --skip-keys=face_recognition --skip-keys=roslibjs --skip-keys=force_proximity_ros --skip-keys=safe_teleop_base"
    - USE_DEB=false
    # - USE_TRAVIS=true
  matrix:
    - ROS_DISTRO=indigo

install:
  - git clone https://github.com/jsk-ros-pkg/jsk_travis.git .travis
  - (cd .travis && git checkout 40640d45c709bdc7d74a1f8983d51d5df553dbc1)

script:
  # build & test ROS packages
  - source .travis/travis.sh
  # build doc
  - cd $TRAVIS_BUILD_DIR/doc
  - unset PYTHONPATH  # cleanup for virtualenv
  - source setup.sh
  - make html

notifications:
  email:
    on_success: always
    on_failure: always
  slack: jsk-robotics:Av7tc8wj3IWkLYvlTzHE7x2g
