# Actuators
actuator_names:
  - left_gripper_prismatic_joint_motor
  - left_gripper_vacuum_pad_tendon_winder
  - left_gripper_finger_yaw_joint_motor
  - left_gripper_finger_tendon_winder
controller_names:
  - prismatic_joint_controller
  - vacuum_pad_tendon_controller
  - finger_yaw_joint_controller
  - finger_tendon_controller

vacuum_pad_motion_limit_config:
  # Lower limit of prismatic joint for free motion of vacuum pad
  prismatic_joint_threshold: 1.72
  # Upper angle limit of vacuum pad joint
  upper_angle_limit: 0

# Flex sensors
flex_names:
  - right
  - left
flex_thresholds:
  - 3400
  - 3400
wind_offset_flex:
  - 0.5
  - 0.5

# Proximity sensors
i2c_multiplexers_to_access_each_sensor:
  # Left finger
  -
    # Root
    - type: 9547
      address: 0x70
      channel: 0
  -
    # Tip
    - type: 9547
      address: 0x70
      channel: 3
  # Right finger
  -
    # Root
    - type: 9547
      address: 0x70
      channel: 4
  -
    # Tip
    - type: 9547
      address: 0x70
      channel: 1
  # Palm
  -
    - type: 9547
      address: 0x70
      channel: 2
    - type: 9546
      address: 0x71
      channel: 0
  -
    - type: 9547
      address: 0x70
      channel: 2
    - type: 9546
      address: 0x71
      channel: 1
  -
    - type: 9547
      address: 0x70
      channel: 2
    - type: 9546
      address: 0x71
      channel: 2
  -
    - type: 9547
      address: 0x70
      channel: 2
    - type: 9546
      address: 0x71
      channel: 3

# FIXME: Reading I2C sensors limits loop rate to 24 Hz
# FIXME: Reading 4 ToF sensors with continuous ranging limits loop rate to 20 Hz
control_rate: 20
