boxes:
- dimensions: [0.35, 0.25, 0.12]
  frame_id: base
  name: cardboard_A
  orientation: [-2.930131094337785e-08, -0.41246350676399623, 8.133334712403232e-09,
    0.9109741245435822]
  position: [1.0457751750946045, 0.18150396645069122, 0.4259834289550781]
- dimensions: [0.4, 0.35, 0.16]
  frame_id: base
  name: cardboard_B
  orientation: [-3.251581811017632e-08, -0.39912072457658876, -3.4510164163496554e-09,
    0.9168983843444473]
  position: [1.0325398445129395, -0.12643444538116455, 0.4657710790634155]
- dimensions: [0.35, 0.63, 0.16]
  frame_id: base
  name: cardboard_C
  orientation: [-2.385071366638366e-08, -0.4014090939766332, 1.1766648895765223e-10,
    0.9158988695663173]
  position: [1.0574169158935547, 1.6689300537109375e-06, -0.07800556719303131]
