prismatic_joint_controller:
  controller:
    package: jsk_2016_01_baxter_apc
    module: calib_required_joint_controller
    type: CalibRequiredJointController
  joint_name: right_gripper_prismatic_joint_motor
  joint_speed: 2.0
  joint_torque_limit: 0.3
  calib_speed: 1.0
  calib_torque_limit: 0.3
  detect_limit_load: 0.17
  motor:
    id: 1
    init: 0
    min: 0
    max: 3300
vacuum_pad_tendon_controller:
  controller:
    package: dynamixel_controllers
    module: joint_position_controller
    type: JointPositionController
  joint_name: right_gripper_vacuum_pad_tendon_winder
  joint_speed: 3.0
  joint_torque_limit: 0.4
  motor:
    id: 4
    init: 570
    min: 1023
    max: 120
finger_yaw_joint_controller:
  controller:
    package: dynamixel_controllers
    module: joint_position_controller
    type: JointPositionController
  joint_name: right_gripper_finger_yaw_joint_motor
  joint_speed: 1.0
  joint_torque_limit: 0.15
  motor:
    id: 2
    init: 250
    min: 250
    max: 650
finger_tendon_controller:
  controller:
    package: dynamixel_controllers
    module: joint_position_controller
    type: JointPositionController
  joint_name: right_gripper_finger_tendon_winder
  joint_speed: 3.0
  joint_torque_limit: 0.4
  motor:
    id: 3
    init: 3530
    min: 3530
    max: 1480
